-- Active: 1716894496133@@127.0.0.1@3306@joeun

DROP TABLE IF EXISTS product;
CREATE TABLE product
(
    no      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id      CHAR(36) NOT NULL DEFAULT(UUID()),
    name    VARCHAR(100) NOT NULL,
    price   INT NOT NULL DEFAULT 0,
    img     TEXT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);